# Creating Arrays

As described in the previous lecture, numpy arrays allow us to write highly readable and performant code when working with batches of numbers. In the next couple lectures, we'll go into a bit more detail about how to create, modify, and retrieve information from arrays.

## Creating Arrays

As we already discussed, the simplest way to create small, custom arrays in numpy is by transforming a list into an array.

In [1]:
#Import numpy (Seriously, we will use the line nearly every time0
import numpy as np

In [2]:
#Create an array from a list
L=[1,2,3,4]
a=np.array(L)
a

array([1, 2, 3, 4])

There are also a number of built in functions for creating np arrays

In [3]:
#Set n=3 for illustration purpose
n=3
#Array of n zeros
np.zeros(n)

array([0., 0., 0.])

In [4]:
#Array on n ones
np.ones(n)

array([1., 1., 1.])

In [5]:
#Random numbers between 0 and 1
np.random.rand(n)

array([0.58473889, 0.78893927, 0.30067052])

In [8]:
#numpy version of range: arange (pronounce a range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#n evenly spaced points. Arguments are first point, last point, number of points
np.linspace(0,9,10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Multidimensional Arrays

In [12]:

n=3
#n by n array of all zeros indexed by a tuple
np.zeros((n,n))

#n by n array of all ones note that the inner argument is a tuple
np.ones((n,n))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# n by n by n array of all ones (a bit harder to visualize)
A3d=np.ones((n,n,n))

You can check shape with either np.shape or A.shape

In [17]:
np.shape(A3d)

(3, 3, 3)

In [18]:
A3d.shape

(3, 3, 3)

In [17]:
### Reshaping

In [20]:
#numbers 0 through 14
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Let's reshape a into a 3 by 5 array. Note that inner argument is not a tuple

In [21]:
A=a.reshape(3,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])