## Accessing Array Elements

Often, we want to access the data contained inside an array, for the purpose of either modifying the data or using it in later computation. For 1d arrays, the simplest way to do this is very similar to how we would do so for a list: 

In [1]:
#As always...
import numpy as np

In [3]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print(a[0],a[3],a[-1])

0 3 9


In [5]:
#first four elements
a[0:4]

array([0, 1, 2, 3])

## Fancy and  Boolean Indexing

Fancy indexing let's you use a list an an index

In [6]:
#entries 4, 5, and 8 of a
L=[4,5,8]
a[L]

array([4, 5, 8])

Boolean logic acts bitwise

In [7]:
a%2==1

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

We can use this to only print the elements of a which taken odd values

In [8]:
a[a%2==1]

array([1, 3, 5, 7, 9])

The array a%2==1 is is called a mask, so we can also write 

In [9]:
mask=(a%2==1)
a[mask]

array([1, 3, 5, 7, 9])

Can compare to another array

In [13]:
#10 random ints between 0 and 10
b=np.random.randint(0,10,10)
b
mask=a>b
a[mask]

array([3, 5, 8, 9])

If we want our mask to impose multiple requirements we use the bitwise 'and'  and 'or' operators & and |

In [15]:
#entries that are greater than 5 and odd
mask1=(a>5) & a%2==1
mask1
a[mask1]

array([7, 9])

In [16]:
#entries that are greater than 5 or odd
mask2=(a>5) | a%2==1
mask2
a[mask2]

array([1, 3, 5, 6, 7, 8, 9])

# Modifiying array entries

Changing the entry of  a single term is straight forward

In [17]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a[5]=50
a

array([ 0,  1,  2,  3,  4, 50,  6,  7,  8,  9])

Can also use boolean indexing 

In [21]:
mask=a%2==1
a[mask]=7
a

array([ 0,  7,  2,  7,  4, 50,  6,  7,  8,  7])

Can assign blocks at a time 

In [23]:
a[2:5]=[1,2,3]
a

array([ 0,  7,  1,  2,  3, 50,  6,  7,  8,  7])

In [24]:
#can even do this
a[a==7]=[111,222,333]
a

array([  0, 111,   1,   2,   3,  50,   6, 222,   8, 333])

In [25]:
#have to be careful, right now there are three entries which are bigger than 100
#This is okay
a[a>100]=[555,555,555]

In [28]:
#This gives an error
#a[a>100]=[555,555]

In [31]:
#Suprisingly, this is okay (broadcasting)
a[a>100]=[777]
a

array([  0, 777,   1,   2,   3,  50,   6, 777,   8, 777])

# Indexing 2d arrays

In [32]:
a=np.arange(15)
A=a.reshape(3,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

First index is row second is columnn

In [33]:
#row 1 column 3
A[1,3]

8

Negative indexing works

In [34]:
#last row, second last column
A[-1,-2]

13

Can print entire rows and columns

In [35]:
#first row
A[0,:]

array([0, 1, 2, 3, 4])

In [36]:
#first column
A[:,0]

array([ 0,  5, 10])

In [37]:
#all of A with double colons
A[:,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
#all of the odd entries in A
mask=A%2==1
A[mask]

array([ 1,  3,  5,  7,  9, 11, 13])

In [39]:
#add 2 to all of the odd entries
A[mask]+=2
A

array([[ 0,  3,  2,  5,  4],
       [ 7,  6,  9,  8, 11],
       [10, 13, 12, 15, 14]])