# Broadcasting 

In [1]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5])

In [3]:
#this produces an error
#a+b

Indeed, adding arrays of different sizes feels "unnatural". But note that the error message said 

"ValueError: operands could not be broadcast together with shapes (3,) (2,)"

It didn't just say "shapes don't match."

Sometimes you **can** add arrays of different shapes and this is called broadcasting


In [20]:
a=np.ones(3)
b=np.zeros(3)
b=b.reshape(1,3)
a,b

(array([1., 1., 1.]), array([[0., 0., 0.]]))

In [21]:
a.shape,b.shape
#first a gets `reshaped from 3 to (1,3)
#now they mmatch, we can add now

((3,), (1, 3))

First rule of broadcasting:
If one array has more dimensions, take the array with fewer dimensions  and 'pad' it with ones __ON THE LEFT__

If you try to type a+b, numpy will automatically convert it to an array with shape (1,3) and then the addition works fine.


In [14]:
a+b
(a+b).shape

(1, 3)

In [16]:
a=np.zeros((3,3))
b=np.arange(3)
print(a.shape,b.shape)
a,b

(3, 3) (3,)


(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([0, 1, 2]))

What happens if we try to add a and b?

By the first rule of broadcasting, b gets padded with a one so now a has shape(3,3) and b has shape (1,3)

### Second rule of broadcasting. 
If arrays have the same number of dimesions, you can stretch out ones

this means that b will get converted from array([0,1,2]) to array([[0,1,2],[0,1,2],[0,1,2]])
is the 3 by 3 array where every row is a copy of the original b

mathematically, we have the formula new_b[i,j]=old_b[j]

axis 0 is the axis we are "streching over" i isn't on the right hand side

In [18]:
a+b
#first thing that happens is b gets reshaped from 3 to 1 by three
#first rule of broadcasting 
#now we are trying to add (3,3) and (1,3)

#now stretch out along the one axis so 
#b gets converted into [[0,1,2],[0,1,2],[0,1,2,]]
#and a was [[0,0,0],[0,0,0],[0,0,0]]

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

### Third rule of broadcasting.

Sometimes you are out of luck. If the arrays have the same number of dimensions, the dimensions don't match, and there is not a one in either location, you can't add, i.e., you can  only stretch ones. 

In [19]:
A=np.zeros((3,4))
B=np.zeros((4,3))

A+B

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

### More Complicated Example

In [25]:
a=np.arange(3)
#a=a.reshape(1,3)
b=2*np.arange(3)
b=b.reshape(3,1)
print(a.shape,b.shape)
a,b

(3,) (3, 1)


(array([0, 1, 2]),
 array([[0],
        [2],
        [4]]))

Can we add? Yes! As long as there is a one in each dimension!

a gets stretched out along dimension 0 to form a 3 by 3 array. We are stretching along axis = so the rule is 
a_new[i,j]=a[j] so a becomes

array([[0,1,2],[0,1,2],[0,1,2]])

b on the other hand gets stretched along axis 1 so it gets obays the rule b_new[i] = b[i,j]

so be gets converted from 0,2,4 to 

array([[0,0,0],[2,2,2],[4,4,4]])

Now, since  a and b are both 3 by 3 we can add

In [26]:
a+b

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]])

Note that a_new and b_new are all "under the hood." You don't actually see them.

In [24]:
np.arange(3)+4

array([4, 5, 6])

4 is stretched to array([4,4,4])

# Normalizing Data

In [27]:
X=np.random.rand(10,3)
X

array([[0.70329441, 0.8747731 , 0.61177929],
       [0.93303465, 0.52526043, 0.18348183],
       [0.85446974, 0.41467252, 0.63297739],
       [0.23810756, 0.26688548, 0.78110255],
       [0.18754975, 0.28775419, 0.05042338],
       [0.84474209, 0.15328828, 0.94012866],
       [0.08906295, 0.99651597, 0.6948436 ],
       [0.10523245, 0.55541998, 0.32278639],
       [0.89623121, 0.61829083, 0.90466743],
       [0.66206417, 0.69026647, 0.16380021]])

Interpretation. Each row is a new person. Each column is a different 'assessment'. Can we manipulate our data so that each column has mean zero and variance 1?

In [28]:
mu=X.mean(axis=0)
mu

array([0.5513789 , 0.53831273, 0.52859907])


What happen if we type X-mu? 

X has shape 10,3 mu has shape 3, so by the first rule of broadcasting, mu gets padded with a one to have shape 1,3.

Then, by the second rule of broadcasting, mu gets stretched out to a ten by 3 matrix where each row is a copy of the original mu

In [31]:
Centered=X-mu
Centered

array([[ 0.15191551,  0.33646037,  0.08318021],
       [ 0.38165575, -0.01305229, -0.34511724],
       [ 0.30309084, -0.12364021,  0.10437832],
       [-0.31327134, -0.27142724,  0.25250347],
       [-0.36382915, -0.25055853, -0.4781757 ],
       [ 0.2933632 , -0.38502445,  0.41152959],
       [-0.46231595,  0.45820324,  0.16624453],
       [-0.44614645,  0.01710726, -0.20581268],
       [ 0.34485231,  0.07997811,  0.37606836],
       [ 0.11068527,  0.15195375, -0.36479886]])

In [32]:
Centered.mean(axis=0)

array([-2.22044605e-17,  1.11022302e-17,  2.22044605e-17])

Okay, now lets make the variance of each column =1

In [33]:
sigma=X.std(axis=0)
sigma

array([0.33483325, 0.25555592, 0.30711366])

In [35]:
Normalized=(X-mu)/sigma

In [36]:
Centered.mean(axis=0),Centered.std(axis=0)

(array([-2.22044605e-17,  1.11022302e-17,  2.22044605e-17]),
 array([0.33483325, 0.25555592, 0.30711366]))

In [37]:
Normalized.mean(axis=0),Normalized.std(axis=0)

(array([-4.44089210e-17,  3.33066907e-17,  8.88178420e-17]),
 array([1., 1., 1.]))

# Linear Algebra 

In [38]:
A=np.arange(15).reshape(5,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [39]:
x=np.ones(3)

What does $A*x$ do?

In [40]:
A*x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

What does it NOT do?

In [41]:
np.matmul(A,x)

array([ 3., 12., 21., 30., 39.])

## Matrix-vector multiplication? 

Recall that multiplication of an $M\times N$ matrix by an $N$ dimensional vector results in a new $M$ dimensional vector $y=Ax$ defined by 
\begin{equation*}
y_i=\sum_jA_{i,j}x_j
\end{equation*}

In [42]:
y=np.matmul(A,x)

# Matrix-Matrix multiplication 

If $A$ is an $M\times N$ matrix and $B$ is an $N\times R$ matrix, then $C=AB$ is an $M\times R$ matrix defined by 

\begin{equation*}
C_{i,j}=\sum_kA_{i,k}B_{k,j}
\end{equation*}

In [43]:
B=np.arange(33).reshape(3,11)
C=np.matmul(A,B)
C.shape

(5, 11)

This doesn't work


In [44]:
BadB=np.arange(22).reshape(2,11)
C=np.matmul(A,BadB)
C.shape


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)