# Quick reminders 

1) Midterm is on Thursday! It starts at 8AM, you get 24 hours, the format is similar to old midterms / discussion / homeworks. Should take about 90 minutes, you are 100% allowed to spend more time within the 24 hours. It is open notes/book/interweb. It is not open other people. The only human being you should correspond with about the exam is me (and Wonjun).  You are allowed to google, and if you find something on stack exchange, that is OKAY. You are not allowed to post a new question on stackexchange. 

2) Mid-quarter feedback survey. Deadline tomorrow July 14th at 1159. 0.25% added to your course grade if you fill it out. 

3) No discussion tomorrow or thursday because of the midterm

# Broadcasting 

In [1]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5])




In [4]:
a+b
#for lists, you concantenate
#[1,2,3]+[4,5]

#for numpy arrays, you add pointwise np.array([1,2])+np.array([3,4])=np.array([1+3,2+4])

#add columns
#this seems kind of silly, but actually, numpy does this sometimes 
#and that is going to be the main focus of the lecture



ValueError: operands could not be broadcast together with shapes (3,) (2,) 

Indeed, adding arrays of different sizes feels "unnatural". But note that the error message said 

"ValueError: operands could not be broadcast together with shapes (3,) (2,)"

It didn't just say "shapes don't match."

Sometimes you **can** add arrays of different shapes and this is called broadcasting


In [7]:
a=np.ones(3)
b=np.zeros(3)
b=b.reshape(1,3)
a,b

(array([1., 1., 1.]), array([[0., 0., 0.]]))

In [9]:
a.shape,b.shape



((3,), (1, 3))

First rule of broadcasting:
If one array has more dimensions, take the array with fewer dimensions  and 'pad' it with ones __ON THE LEFT__

If you try to type a+b, numpy will automatically convert it to an array with shape (1,3) and then the addition works fine.


In [12]:
(a+b).shape
#in this process
# is first converted from a 3, arrray to a 1,3 array and then added to b which is already 1,3

(1, 3)

In [13]:
#Example 2
a=np.zeros((3,3))
b=np.arange(3)
print(a.shape,b.shape)
a,b

#first rule of broad casting says b gets converted to (1,3)
#so now we are trying to add (3,3) and (1,3)
''' stretching out
[0,1,2]
[0,1,2]
[0,1,2]
'''

(3, 3) (3,)


(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([0, 1, 2]))

What happens if we try to add a and b?

By the first rule of broadcasting, b gets padded with a one so now a has shape(3,3) and b has shape (1,3)

### Second rule of broadcasting. 
If arrays have the same number of dimesions, you can stretch out ones

this means that b will get converted from array([0,1,2]) to array([[0,1,2],[0,1,2],[0,1,2]])
is the 3 by 3 array where every row is a copy of the original b

mathematically, we have the formula new_b[i,j]=old_b[j]

axis 0 is the axis we are "streching over" i isn't on the right hand side

In [14]:
a+b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

### Third rule of broadcasting.

Sometimes you are out of luck. If the arrays have the same number of dimensions, the dimensions don't match, and there is not a one in either location, you can't add, i.e., you can  only stretch ones. 

In [16]:
A=np.zeros((3,4))
B=np.zeros((4,3))
A+B
#no padding because there is already the same # of dimensions
#can only stretch out ones

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

### More Complicated Example

In [20]:
a=np.arange(3)
a=a.reshape(1,3)
b=2*np.arange(3)
b=b.reshape(3,1)
print(a.shape,b.shape)
print(a)
print(b)

#first you stretch a so that that is shape 3,3
'''[[0,1,2]]
goes to 
[[0,1,2]
[0,1,2]
[0,1,2]]
#then 
[[0],[2],[4]]
#gets stretched to 
[[0,0,0],
[2,2,2],
[4,4,4]]
now you do the addition 
[[0,1,2],
[2,3,4]
[4,5,6]]'''


(1, 3) (3, 1)
[[0 1 2]]
[[0]
 [2]
 [4]]


'[[0,1,2]]\ngoes to \n[[0,1,2]\n[0,1,2]\n[0,1,2]]\n#then \n[[0],[2],[4]]\n#gets stretched to \n[[0,0,0],\n[2,2,2],\n[4,4,4]]\nnow you do the addition \n[[0,1,2],\n[2,3,4]\n[4,5,6]]'

Can we add? Yes! As long as there is a one in each dimension!

a gets stretched out along dimension 0 to form a 3 by 3 array. We are stretching along axis = so the rule is 
a_new[i,j]=a[j] so a becomes

array([[0,1,2],[0,1,2],[0,1,2]])

b on the other hand gets stretched along axis 1 so it gets obays the rule b_new[i] = b[i,j]

so be gets converted from 0,2,4 to 

array([[0,0,0],[2,2,2],[4,4,4]])

Now, since  a and b are both 3 by 3 we can add

In [19]:
a+b

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]])

Note that a_new and b_new are all "under the hood." You don't actually see them.

4 is stretched to array([4,4,4])

# Normalizing Data

In [21]:
X=np.random.rand(10,3)
X

array([[0.80061173, 0.66389637, 0.56487929],
       [0.53324637, 0.27939957, 0.45265259],
       [0.75248473, 0.322686  , 0.60901188],
       [0.99892723, 0.97157201, 0.96391642],
       [0.64439165, 0.15514202, 0.21865219],
       [0.13223619, 0.9542069 , 0.71449292],
       [0.47327195, 0.6101721 , 0.73466617],
       [0.00261848, 0.71013836, 0.55489241],
       [0.04066312, 0.55383787, 0.87175821],
       [0.19447588, 0.39010269, 0.50491457]])

Interpretation. Each row is a new person. Each column is a different 'assessment'. Can we manipulate our data so that each column has mean zero and variance 1?

In [56]:
#in scientific applications, 
#it is nice a lot of the time to make each column of a data matrix 
#have mean zero and variance one

#X has shape 10,3

mu1=X.mean(axis=0) #shape 3
mu2=X.mean(axis=1) #shape 10
mu1,mu2

(array([0.45729273, 0.56111539, 0.61898367]),
 array([0.67646246, 0.42176618, 0.5613942 , 0.97813855, 0.33939529,
        0.600312  , 0.60603674, 0.42254975, 0.48875307, 0.36316438]))

What happen if we type X-mu? 

X has shape 10,3 mu has shape 3, so by the first rule of broadcasting, mu gets padded with a one to have shape 1,3.

Then, by the second rule of broadcasting, mu gets stretched out to a ten by 3 matrix where each row is a copy of the original mu

In [32]:
#X-mu #will this make sense????
X.shape, mu.shape
#what is the first thing that happens to mu according to rules of broadcasting?
#pad on the left with ones so now mu is (1,3)

#now the second thing that happens is it gets stretched out into a 10,3 array
# by the second rule of broadcasting
centered=X-mu

In [33]:
centered

array([[ 0.343319  ,  0.10278098, -0.05410438],
       [ 0.07595364, -0.28171582, -0.16633107],
       [ 0.295192  , -0.23842939, -0.00997179],
       [ 0.5416345 ,  0.41045662,  0.34493276],
       [ 0.18709892, -0.40597337, -0.40033147],
       [-0.32505655,  0.39309152,  0.09550925],
       [ 0.01597921,  0.04905671,  0.11568251],
       [-0.45467426,  0.14902297, -0.06409126],
       [-0.41662961, -0.00727752,  0.25277455],
       [-0.26281685, -0.1710127 , -0.1140691 ]])

Okay, now lets make the variance of each column =1

In [34]:
sigma=X.std(axis=0)
sigma

array([0.3308244 , 0.26239264, 0.20333606])

In [37]:
normalized = centered/sigma

In [42]:
normalized.mean(axis=0)

array([ 5.55111512e-17, -3.21964677e-16,  1.66533454e-16])

In [43]:
#so for review to normalize your data so that all columns have mean zero and std 1
mu=X.mean(axis=0)
sigma=X.std(axis=0)
Normalized_Data=(X-mu)/sigma



# Linear Algebra 

In [45]:
A=np.arange(15).reshape(5,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [47]:
x=np.ones(3)
A.shape,x.shape

((5, 3), (3,))

What does $A*x$ do?

In [49]:
A*x
#uses broadcasting rules 
#then does pointwise multiplication

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

What does it NOT do? - does not perform matrix multiplication 

In [50]:
np.matmul(A,x)

array([ 3., 12., 21., 30., 39.])

## Matrix-vector multiplication? 

Recall that multiplication of an $M\times N$ matrix by an $N$ dimensional vector results in a new $M$ dimensional vector $y=Ax$ defined by 
\begin{equation*}
y_i=\sum_jA_{i,j}x_j
\end{equation*}

So for example
\begin{equation*}
y[0] = A[0,0]x[0] + A[0,1]x[1]+ A[0,2]x[2]+ A[0,3]x[3]+ A[0,3]x[3]
\end{equation*}

In [ ]:
np.matmul(A,x)

# Matrix-Matrix multiplication 

If $A$ is an $M\times N$ matrix and $B$ is an $N\times R$ matrix, then $C=AB$ is an $M\times R$ matrix defined by 

\begin{equation*}
C_{i,j}=\sum_kA_{i,k}B_{k,j}
\end{equation*}

In [53]:
B=np.arange(33).reshape(3,11)
A.shape,B.shape
C=np.matmul(A,B)
C.shape

(5, 11)

This doesn't work


In [54]:
BadB=np.arange(22).reshape(2,11)
BadC=np.matmul(A,BadB)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)