# Broadcasting 

In [1]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5])

In [2]:
#This produces an error
#a+b

Indeed, adding arrays of different sizes feels "unnatural". But note that the error message said 

"ValueError: operands could not be broadcast together with shapes (3,) (2,)"

It didn't just say "shapes don't match."

Sometimes you **can** add arrays of different shapes and this is called broadcasting


In [6]:
a=np.ones(3)
b=np.zeros(3)
#b=b.reshape(3,1)
a,b
#a+b

(array([1., 1., 1.]), array([0., 0., 0.]))

In [5]:
#It looks like we should be able to add a and b,but 
a.shape,b.shape

((3,), (1, 3))

First rule of broadcasting:
If one array has more dimensions, take the array with fewer dimensions  and 'pad' it with ones __ON THE LEFT__

If you try to type a+b, numpy will automatically convert it to an array with shape (1,3) and then the addition works fine.


In [6]:
a+b

array([[1., 1., 1.]])

In [7]:
#Example 2
a=np.zeros((3,3))
b=np.arange(3)
print(a.shape,b.shape)
a,b

(3, 3) (3,)


(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([0, 1, 2]))

What happens if we try to add a and b?

By the first rule of broadcasting, b gets padded with a one so now a has shape(3,3) and b has shape (1,3)

### Second rule of broadcasting. 
If arrays have the same number of dimesions, you can stretch out ones

this means that b will get converted from array([0,1,2]) to array([[0,1,2],[0,1,2],[0,1,2]])
is the 3 by 3 array where every row is a copy of the original b

mathematically, we have the formula new_b[i,j]=old_b[j]

axis 0 is the axis we are "streching over" i isn't on the right hand side

In [8]:
a+b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

### Third rule of broadcasting.

Sometimes you are out of luck. If the arrays have the same number of dimensions, the dimensions don't match, and there is not a one in either location, you can't add, i.e., you can  only stretch ones. 

In [9]:
#This gives you a value error
#A=np.zeros((3,4))
#B=np.zeros((4,3))
#A+B

### More Complicated Example

In [10]:
a=np.arange(3)
a=a.reshape(1,3)
b=2*np.arange(3)
b=b.reshape(3,1)
print(a.shape,b.shape)
a,b

(1, 3) (3, 1)


(array([[0, 1, 2]]),
 array([[0],
        [2],
        [4]]))

Can we add? Yes! As long as there is a one in each dimension!

a gets stretched out along dimension 0 to form a 3 by 3 array. We are stretching along axis = so the rule is 
a_new[i,j]=a[j] so a becomes

array([[0,1,2],[0,1,2],[0,1,2]])

b on the other hand gets stretched along axis 1 so it gets obays the rule b_new[i,j] = b[i]

so be gets converted from 0,2,4 to 

array([[0,0,0],[2,2,2],[4,4,4]])

Now, since  a and b are both 3 by 3 we can add

In [11]:
a+b

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]])

Note that a_new and b_new are all "under the hood." You don't actually see them.

In [12]:
#Example
np.arange(3)+4

array([4, 5, 6])

4 is stretched to array([4,4,4])

# Normalizing Data

In [13]:
#Here is some random data
X=np.random.rand(10,3)
X

array([[0.5472717 , 0.93094639, 0.62135154],
       [0.12585206, 0.75358247, 0.76279303],
       [0.59367895, 0.31972704, 0.8196078 ],
       [0.89381096, 0.56940916, 0.88230661],
       [0.75234833, 0.18351278, 0.67783375],
       [0.39171308, 0.05580479, 0.97280037],
       [0.60432315, 0.41634536, 0.03631275],
       [0.50113973, 0.21371594, 0.96771802],
       [0.71521903, 0.58328626, 0.93313476],
       [0.76836352, 0.98497206, 0.0627713 ]])

Interpretation. Each row is a new person. Each column is a different 'assessment'. Can we manipulate our data so that each column has mean zero and variance 1?

In [14]:
#mean of each column
mu=X.mean(axis=0)
mu

array([0.58937205, 0.50113023, 0.67366299])

What happen if we type X-mu? 

X has shape 10,3 mu has shape 3, so by the first rule of broadcasting, mu gets padded with a one to have shape 1,3.

Then, by the second rule of broadcasting, mu gets stretched out to a ten by 3 matrix where each row is a copy of the original mu

In [15]:
Centered = X-mu
Centered

array([[-0.04210035,  0.42981617, -0.05231145],
       [-0.46351999,  0.25245224,  0.08913004],
       [ 0.0043069 , -0.18140318,  0.14594481],
       [ 0.30443891,  0.06827893,  0.20864362],
       [ 0.16297628, -0.31761745,  0.00417076],
       [-0.19765897, -0.44532543,  0.29913738],
       [ 0.0149511 , -0.08478486, -0.63735025],
       [-0.08823232, -0.28741428,  0.29405503],
       [ 0.12584698,  0.08215604,  0.25947177],
       [ 0.17899147,  0.48384183, -0.61089169]])

In [16]:
Centered.mean(axis=0)

array([ 2.22044605e-17, -2.22044605e-17, -5.55111512e-17])

Okay, now lets make the variance of each column =1

In [17]:
sigma = X.std(axis=0)
sigma

array([0.20756663, 0.30263621, 0.3313927 ])

In [18]:
Normalized=(X-mu)/sigma
Normalized

array([[-0.20282813,  1.42024038, -0.15785336],
       [-2.23311425,  0.83417725,  0.26895595],
       [ 0.02074946, -0.59941004,  0.44039837],
       [ 1.46670451,  0.2256139 ,  0.6295963 ],
       [ 0.78517573, -1.04950246,  0.01258554],
       [-0.9522676 , -1.47148761,  0.90266737],
       [ 0.07203037, -0.28015439, -1.92324769],
       [-0.42507952, -0.94970222,  0.88733103],
       [ 0.60629681,  0.27146796,  0.78297371],
       [ 0.86233262,  1.59875723, -1.84340721]])

In [19]:
Normalized.mean(axis=0), Normalized.std(axis=0)

(array([ 1.11022302e-16, -4.44089210e-17, -1.99840144e-16]),
 array([1., 1., 1.]))

In [20]:
#Note that the rows do not have mean zero or variance 1

Normalized.mean(axis=1), Normalized.std(axis=1)


(array([ 0.35318629, -0.37666035, -0.0460874 ,  0.77397157, -0.08391373,
        -0.50702928, -0.71045724, -0.16248357,  0.55357949,  0.20589421]),
 array([0.75474455, 1.33283772, 0.42712275, 0.51685565, 0.75210598,
        1.01909464, 0.86954166, 0.77261041, 0.2121224 , 1.47993413]))

# Linear Algebra 

In [22]:
A=np.arange(15).reshape(5,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [23]:
x=np.ones(3)

What does $A*x$ do?

In [24]:
A*x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

What does it NOT do?

array([ 3., 12., 21., 30., 39.])

## Matrix-vector multiplication? 

Recall that multiplication of an $M\times N$ matrix by an $N$ dimensional vector results in a new $M$ dimensional vector $y=Ax$ defined by 
\begin{equation*}
y_i=\sum_jA_{i,j}x_j
\end{equation*}

In [27]:
np.matmul(A,x)

array([ 3., 12., 21., 30., 39.])

# Matrix-Matrix multiplication 

If $A$ is an $M\times N$ matrix and $B$ is an $N\times R$ matrix, then $C=AB$ is an $M\times R$ matrix defined by 

\begin{equation*}
C_{i,j}=\sum_kA_{i,k}B_{k,j}
\end{equation*}

In [29]:
B=np.arange(33).reshape(3,11)
C=np.matmul(A,B)
C.shape

(5, 11)

This doesn't work


In [30]:
BadB=np.arange(22).reshape(2,11)
BadC=np.matmul(A,BadB)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)