# Broadcasting 

Indeed, adding arrays of different sizes feels "unnatural". But note that the error message said 

"ValueError: operands could not be broadcast together with shapes (3,) (2,)"

It didn't just say "shapes don't match."

Sometimes you **can** add arrays of different shapes and this is called broadcasting


First rule of broadcasting:
If one array has more dimensions, take the array with fewer dimensions  and 'pad' it with ones __ON THE LEFT__

If you try to type a+b, numpy will automatically convert it to an array with shape (1,3) and then the addition works fine.


What happens if we try to add a and b?

By the first rule of broadcasting, b gets padded with a one so now a has shape(3,3) and b has shape (1,3)

### Second rule of broadcasting. 
If arrays have the same number of dimesions, you can stretch out ones

this means that b will get converted from array([0,1,2]) to array([[0,1,2],[0,1,2],[0,1,2]])
is the 3 by 3 array where every row is a copy of the original b

mathematically, we have the formula new_b[i,j]=old_b[j]

axis 0 is the axis we are "streching over" i isn't on the right hand side

### Third rule of broadcasting.

Sometimes you are out of luck. If the arrays have the same number of dimensions, the dimensions don't match, and there is not a one in either location, you can't add, i.e., you can  only stretch ones. 

### More Complicated Example

Can we add? Yes! As long as there is a one in each dimension!

a gets stretched out along dimension 0 to form a 3 by 3 array. We are stretching along axis = so the rule is 
a_new[i,j]=a[j] so a becomes

array([[0,1,2],[0,1,2],[0,1,2]])

b on the other hand gets stretched along axis 1 so it gets obays the rule b_new[i] = b[i,j]

so be gets converted from 0,2,4 to 

array([[0,0,0],[2,2,2],[4,4,4]])

Now, since  a and b are both 3 by 3 we can add

Note that a_new and b_new are all "under the hood." You don't actually see them.

4 is stretched to array([4,4,4])

# Normalizing Data

Interpretation. Each row is a new person. Each column is a different 'assessment'. Can we manipulate our data so that each column has mean zero and variance 1?

What happen if we type X-mu? 

X has shape 10,3 mu has shape 3, so by the first rule of broadcasting, mu gets padded with a one to have shape 1,3.

Then, by the second rule of broadcasting, mu gets stretched out to a ten by 3 matrix where each row is a copy of the original mu

Okay, now lets make the variance of each column =1

# Linear Algebra 

What does $A*x$ do?

What does it NOT do?

array([ 3., 12., 21., 30., 39.])

## Matrix-vector multiplication? 

Recall that multiplication of an $M\times N$ matrix by an $N$ dimensional vector results in a new $M$ dimensional vector $y=Ax$ defined by 
\begin{equation*}
y_i=\sum_jA_{i,j}x_j
\end{equation*}

# Matrix-Matrix multiplication 

If $A$ is an $M\times N$ matrix and $B$ is an $N\times R$ matrix, then $C=AB$ is an $M\times R$ matrix defined by 

\begin{equation*}
C_{i,j}=\sum_kA_{i,k}B_{k,j}
\end{equation*}

This doesn't work
