# Creating Arrays

As described in the previous lecture, numpy arrays allow us to write highly readable and performant code when working with batches of numbers. In the next couple lectures, we'll go into a bit more detail about how to create, modify, and retrieve information from arrays.

## Creating Arrays

As we already discussed, the simplest way to create small, custom arrays in numpy is by transforming a list into an array.

In [1]:
#Seriously, we will use the line nearly every time
import numpy as np

In [2]:
L=[1,2,3,4]
a=np.array(L)
a

array([1, 2, 3, 4])

There are also a number of built in functions for creating np arrays

In [3]:
#Array of n zeros

n=3
np.zeros(n)

array([0., 0., 0.])

In [4]:
#Array on n ones
np.ones(n)

array([1., 1., 1.])

In [5]:
#Random numbers between 0 and 1
np.random.rand(n)

array([0.56814748, 0.21764489, 0.30562588])

In [6]:
#numpy version of range: arange (pronounce a range)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#n evenly spaced points. Arguments are first point, last point, number of points

n=11
np.linspace(0,1,11)



array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multidimensional Arrays

In [12]:
#n by n array of all ones note that the inner argument is a tuple

n=3
A=np.ones((n,n))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# n by n by n array of all ones (a bit harder to visualize)
A3d=np.ones((n,n,n))
A3d

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

You can check shape with either np.shape or A.shape

In [15]:
print(np.shape(A),A.shape)

(3, 3) (3, 3)


In [16]:
A3d.shape

(3, 3, 3)

In [17]:
### Reshaping

In [18]:
#numbers 0 through 14
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Let's reshape a into a 3 by 5 array. Note that inner argument is not a tuple

In [21]:
A=a.reshape(3,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])